node {
   def commit_id
   stage('Preparation') {
     checkout scm
     sh "git rev-parse --short HEAD > .git/commit-id"                        
     commit_id = readFile('.git/commit-id').trim()
   }
   stage('test') {
     nodejs(nodeJSInstallationName: 'NodeJS') {
       sh 'npm install --only=dev'
       sh 'npm test'
     }
   }
   stage('docker build/push') {
     docker.withRegistry('https://github.com/ronen232/docker-cicd', 'cef71b4f-08bb-4552-b8b9-5652659c9b1c') {
       def app = docker.build("ronen232/docker-nodejs-demo:${commit_id}", '.').push()
     }
   }
}
